name: Build EXE with PyInstaller on Push

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest  # 选择 Windows 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # 设置你的 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # 安装 PyInstaller
        pip install -r requirements.txt  # 如果有其他依赖

    - name: Build the EXE using PyInstaller
      run: |
        pyinstaller --onefile --windowed -n jks-pkcs12-reader --add-data "lang_en.json;." --add-data "lang_zh.json;." main.py  # 根据你的 Python 脚本修改文件名

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v2
      with:
        name: myprogram
        path: dist/jks-pkcs12-reader.exe  # PyInstaller 输出的 EXE 文件路径
