name: Build EXE with PyInstaller on Push

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest  # 选择 Windows 环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # 设置你的 Python 版本

    - name: Set up virtual environment
      run: |
        python -m venv venv  # 创建虚拟环境
        venv\Scripts\activate  # 激活虚拟环境

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pyinstaller  # 安装 PyInstaller
        pip install -r requirements.txt  # 如果有其他依赖

    - name: Build the EXE using PyInstaller
      run: |
        pyinstaller --onefile --windowed -n jks-pkcs12-reader --add-data "lang_en.json;." --add-data "lang_zh.json;." --add-data "public.xml;androguard\core\resources" main.py  # 根据你的 Python 脚本修改文件名

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: myprogram-${{ github.ref_name }}
        path: dist/jks-pkcs12-reader.exe  # 生成的 EXE 文件路径

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        files: dist/jks-pkcs12-reader.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
